// 2단계: 요약 — 원본 텍스트를 "씬 스크립트(script.json)"로 변환한다.
//
// 두 가지 경로:
//  (A) ANTHROPIC_API_KEY 가 있으면 Claude API로 고품질 씬 구조를 생성(프롬프트 캐시 사용).
//  (B) 키가 없으면 추출식 폴백으로 핵심 문장을 골라 기본 씬을 구성.
//
// 어느 경우든 결과 스키마는 동일하다:
//  { meta:{title,subtitle,lang,topic,source,voice}, scenes:[{id,heading,visual,data,lines[]}] }
//
// visual 타입: title | stat | list | compare | bars | cta

const MODEL = process.env.HF_LLM_MODEL || "claude-sonnet-4-6";

const SYSTEM = `당신은 모션그래픽 영상의 기획자다. 주어진 원문을 60~80초 분량의 한국어 설명 영상 스크립트로 압축한다.
규칙:
- 5~7개의 씬으로 구성한다.
- 각 씬은 한 가지 메시지만 담는다.
- lines 는 내레이션이자 화면 자막이다. 한 line 은 12~22자 내외의 짧은 구어체 문장.
- 숫자/통계가 있으면 visual:"stat" 으로, 대비가 있으면 "compare", 항목 나열은 "list", 수치 비교는 "bars" 로 연출한다.
- 첫 씬은 "title", 마지막 씬은 "cta".
- 반드시 아래 JSON 스키마만 출력한다(설명·마크다운 금지).
스키마:
{"meta":{"title":string,"subtitle":string},"scenes":[{"heading":string,"visual":"title|stat|list|compare|bars|cta","data":object,"lines":string[]}]}
data 예시:
- stat: {"value":"15%","caption":"2028년 기업 의사결정","sub":"가트너 전망"}
- list: {"items":["목표 분해","도구 사용","자기 검증","장기 기억"]}
- compare: {"left":{"title":"기존 AI","points":["한 번 묻고","한 번 답함"]},"right":{"title":"에이전틱 AI","points":["스스로 계획","도구 사용","반복 실행"]}}
- bars: {"unit":"%","items":[{"label":"2026","value":40},{"label":"2030","value":100}]}
- title/cta: {}`;

export async function summarize({ text, title, source, lang = "ko", topic, voice = "Yuna" }) {
  const key = process.env.ANTHROPIC_API_KEY;
  let script;
  if (key) {
    script = await summarizeLLM({ text, title, topic, key });
  } else {
    script = extractiveFallback({ text, title, topic });
  }
  // 메타 보강 + 씬 id 부여
  script.meta = {
    title: script.meta?.title || title,
    subtitle: script.meta?.subtitle || "",
    lang,
    topic: topic || title,
    source: source || "",
    voice,
  };
  script.scenes = (script.scenes || []).map((s, i) => ({
    id: `scene-${i + 1}`,
    heading: s.heading || "",
    visual: s.visual || (i === 0 ? "title" : "list"),
    data: s.data || {},
    lines: (s.lines || []).filter(Boolean),
  }));
  return script;
}

async function summarizeLLM({ text, title, topic, key }) {
  const body = {
    model: MODEL,
    max_tokens: 4000,
    system: [
      { type: "text", text: SYSTEM, cache_control: { type: "ephemeral" } },
    ],
    messages: [
      {
        role: "user",
        content: [
          {
            type: "text",
            text: `제목: ${title}\n주제 힌트: ${topic || "(자동)"}\n\n원문:\n${text}`,
            cache_control: { type: "ephemeral" },
          },
          { type: "text", text: "위 원문을 스키마에 맞는 JSON 스크립트로 변환해줘." },
        ],
      },
    ],
  };
  const res = await fetch("https://api.anthropic.com/v1/messages", {
    method: "POST",
    headers: {
      "x-api-key": key,
      "anthropic-version": "2023-06-01",
      "content-type": "application/json",
    },
    body: JSON.stringify(body),
  });
  if (!res.ok) throw new Error(`Claude API ${res.status}: ${await res.text()}`);
  const data = await res.json();
  const txt = data.content.map((b) => b.text || "").join("");
  const json = txt.slice(txt.indexOf("{"), txt.lastIndexOf("}") + 1);
  return JSON.parse(json);
}

// 화면용 짧은 키프레이즈. 말줄임표(…) 없이 단어 경계에서 깔끔히 끊는다.
export function keyphrase(s, max = 18) {
  s = String(s).replace(/\s+/g, " ").trim();
  if (s.length <= max) return s;
  const comma = s.search(/[,，]/);
  if (comma >= 4 && comma <= max) return s.slice(0, comma);
  const cut = s.slice(0, max);
  const sp = cut.lastIndexOf(" ");
  return (sp >= 4 ? cut.slice(0, sp) : cut).replace(/[\s,·]+$/, "");
}

// 자막/보이스용. 긴 문장을 "자르지 않고" 자막 청크로 분할(쉼표 → 공백 경계).
export function splitCaption(s, max = 34) {
  s = String(s).replace(/\s+/g, " ").trim();
  const out = [];
  let cur = "";
  for (const part of s.split(/(?<=[,，])\s*/).filter(Boolean)) {
    if ((cur + part).length > max && cur) { out.push(cur.trim()); cur = part; }
    else cur += part;
  }
  if (cur.trim()) out.push(cur.trim());
  // 여전히 긴 청크는 공백 기준으로 추가 분할(여전히 잘라내지 않음)
  const final = [];
  for (const p of out) {
    if (p.length <= max) { final.push(p); continue; }
    let c = "";
    for (const w of p.split(" ")) {
      if ((c + " " + w).trim().length > max && c) { final.push(c.trim()); c = w; }
      else c = (c + " " + w).trim();
    }
    if (c) final.push(c);
  }
  return final;
}

// UI/잡음 문장 제거용
const JUNK =
  /(this content|generated by|음성으로 기사 듣기|구독|뉴스레터|cookie|쿠키|로그인|저작권|©|https?:\/\/|www\.)/i;

// 키가 없을 때: 문장 분할 → 잡음 제거 → 핵심 문장 추출 → 간결화 → 기본 씬 구성.
// (주의: 추출식 폴백은 한계가 있다. 고품질 결과는 ANTHROPIC_API_KEY 또는 에이전트가
//  직접 작성한 script.json 을 쓰는 것을 권장 — README/SKILL 참조.)
function extractiveFallback({ text, title, topic }) {
  const sentences = text
    .split(/(?<=[.!?。])\s+|(?<=다\.)\s+/)
    .map((s) => s.trim())
    .filter((s) => s.length >= 8 && s.length <= 90)
    .filter((s) => !JUNK.test(s))
    // 한글 비중이 40% 이상인 문장만(영문 UI 텍스트 배제)
    .filter((s) => (s.match(/[가-힣]/g) || []).length >= s.length * 0.4);
  const uniq = [...new Set(sentences)];
  const score = (s) =>
    (/\d/.test(s) ? 3 : 0) +
    Math.min(s.length / 16, 2) +
    (/(중요|핵심|반드시|결국|즉|돌파|급증|넘어|최초|최대|처음)/.test(s) ? 2 : 0);
  const ranked = uniq.sort((a, b) => score(b) - score(a)).slice(0, 8);

  const scenes = [
    {
      heading: keyphrase(title, 20),
      visual: "title",
      data: { title: keyphrase(title, 20), subtitle: topic ? keyphrase(topic, 24) : "" },
      lines: ["핵심을 빠르게 정리했습니다."],
    },
  ];
  // 2문장씩 묶어 list 씬으로.
  //  - 화면 항목(items): 짧은 키프레이즈(잘림/말줄임표 없음)
  //  - 자막+보이스(lines): 문장 전체를 청크로 분할 → 더 많은 내용이 자막/음성으로 전달
  const chunk = 2;
  for (let i = 0; i < ranked.length && scenes.length < 5; i += chunk) {
    const group = ranked.slice(i, i + chunk);
    scenes.push({
      heading: "",
      visual: "list",
      data: { items: group.map((l) => keyphrase(l, 18)) },
      lines: group.flatMap((l) => splitCaption(l, 34)),
    });
  }
  scenes.push({
    heading: "",
    visual: "cta",
    data: {},
    lines: ["자세한 내용은 원문에서 확인하세요."],
  });
  return { meta: { title, subtitle: topic || "" }, scenes };
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const { readFile } = await import("node:fs/promises");
  const file = process.argv[2];
  const text = await readFile(file, "utf8");
  const out = await summarize({ text, title: "test", lang: "ko" });
  console.log(JSON.stringify(out, null, 2));
}
